version: '3'

services:
  postgres:
    image: postgres
    restart: always
    ports:
      - 5433:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: integration_tests_db
    volumes:
      - postgres_data:/var/lib/postgresql

volumes:
  postgres_data: